### ISSUE TITLE
Tracking Issue for Unimplemented Gitea APIs

### ISSUE THREAD

**Issue by shrik450** [AllSpiceIO/py-allspice#17]
I went through the swagger definition for AllSpice hub 1.19 and checked which of those are present in py-gitea and which aren't. After some pre-filtering etc. here's a list of APIs I think are reasonably important. Not all of these are the same priority, and we might not end up implementing some of these.

Since most of these are base gitea endpoints and not unique to AllSpice Hub, we'll also try to get them upstreamed into py-gitea.

# List of APIs in AllSpice not present in py-allspice

## Admin

- [ ] Cron
- [ ] Hooks (Admin-level hooks)
- [ ] Unadopted Repostiories
- [ ] Add/Remove public keys from user

## Organisations

- [ ] Get & Create orgs

  Note: These technically _are_ implemented - but with the admin routes. It
  might be better to support the bare `/orgs` route instead of the admin
  routes.

- [ ] Org Hooks
- [ ] Org Level Labels
- [ ] Publicisize/Depublicize org memebership
- [ ] Add/remove a repo to a team

## Packages

None of these are present. For reference, the Gitea package API allows getting
and deleting packages, but not creating a new one.

## Issues

- [x] Comment APIs: Only getting the comments is supported - covered in #20 
- [x] Issue attachment APIs - covered in #20 
- [ ] Labels, including adding labels to issues etc.

## Repositories

- [ ] Repo Migrations: There is an open PR on py-gitea for this.
- [ ] Branch Protections
- [x] Pull Request APIs - [ ] all of them
- [ ] Mirrors
- [x] Releases
- [ ] Wiki APIs
- [ ] Secrets - These aren't on the swagger defs yet.

## Categories not considered for this

- Misc
- Notifications
- Settings
- User

**Comment by shrik450** [comment]
My current thoughts on prioritisation:

- Issue APIs for automation with CI 
- PR APIs, ditto
- The rest when the need comes up for them
